sudo: false

language: perl
perl:
  - "5.14"
  - "5.18"
  - "5.20"

env: PERL_CPANM_OPT="--notest --force --skip-satisfied"

before_install:

install:
 - cpanm --notest --metacpan --skip-satisfied

notifications:
  irc: "irc.freenode.org#i-mscp-dev"
  email: false

script: perl ./engine/PerlLib/test/iMSCP/DirTests.pm
