sudo: false

language: perl

perl:
  - "5.14"
  - "5.18"
  - "5.20"

install:
  - perl -v

notifications:
  irc:
    - "irc.freenode.org#i-mscp-dev"
    - "irc.freenode.org#i-mscp"
  email: false

script:
  - perl ./test/perlunit.pl
