sudo: true

language: perl

perl:
  - "5.14"
  - "5.18"
  - "5.20"
  - "5.22"

install:
  - perl -v

notifications:
  irc:
    - "irc.freenode.org#i-mscp-dev"
    - "irc.freenode.org#i-mscp"
  email: false

script:
  - sudo perl ./test/perlunit.pl
