sudo: false

#language: perl

#perl:
#  - "5.14"
#  - "5.18"
#  - "5.20"
#  - "5.22" # NOT YET AVAILABLE VIA PERLBREW ON TRAVIS

addons:
  apt:
    packages:
    - fakeroot

#install:
#  - perl -v

notifications:
  irc:
    - "irc.freenode.org#i-mscp-dev"
    - "irc.freenode.org#i-mscp"
  email: false

script:
  - perlbrew exec --with 5.14,5.16,5.18,5.20,5.21 fakeroot perl ./test/perlunit.pl
