sudo: false

language: perl

#perl:
#  - "5.14"
#  - "5.18"
#  - "5.20"
#  - "5.22" # NOT YET AVAILABLE VIA PERLBREW ON TRAVIS

addons:
  apt:
    packages:
    - fakeroot

install:
  - perl -v

notifications:
  irc:
    - "irc.freenode.org#i-mscp-dev"
    - "irc.freenode.org#i-mscp"
  email: false

script:
  - fakeroot perlbrew exec --with perl-5.14,perl-5.16,perl-5.18,perl-5.20,perl-5.21 ./test/perlunit.pl
