sudo: false

language: perl

addons:
  apt:
    packages:
    - fakeroot

before_install:
  - cd ./test

notifications:
  irc:
    - "irc.freenode.org#i-mscp-dev"
    - "irc.freenode.org#i-mscp"
  email: false
