sudo: false

language: perl

perl:
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.21"

cache:
  directories:
    - $HOME/.composer/cache

addons:
  apt:
    packages:
      - curl
      - fakeroot
      - php5-cli
      - php5-intl
      - php5-mcrypt
      - whiptail

env: PERL_CPANM_OPT="--quiet --notest --force --skip-satisfied"

before_install:
 - curl -sS https://getcomposer.org/installer | php

install:
  - cpanm Expect
  - cpanm Crypt::Blowfish
  - cpanm Crypt::CBC
  - cpanm Crypt::Eksblowfish::Bcrypt
  - cpanm Crypt::Rijndael
  - travis_retry composer install --no-interaction --ignore-platform-reqs --prefer-source

notifications:
  irc:
    - "irc.freenode.org#i-mscp-dev"
    - "irc.freenode.org#i-mscp"
  email: false

script:
  - fakeroot perl ./test/perlunit.pl
  - ./vendor/bin/phpunit
