sudo: false

language: perl
perl:
  - "5.14"
  - "5.18"
  - "5.20"

before_install:

install:
 - perl -v

notifications:
  irc: "irc.freenode.org#i-mscp-dev"
  email: true

script: perl ./tests/execute.pl
